Feature/google_auth
ZZH0C/react-seed pull request #2
Opened 2021-07-09 10:16 UTC by ZZH0C

2021-07-09 13:54 UTC, AnastasiaKozhemyachko commented on src/components/HeaderUser/HeaderUser.tsx
> +    if (userData) {
Don't use too much nesting, it is better to do
```
if (!userData) {
  setProfileSrc(...
  return;
}
if ('profileObj'...
```

2021-07-09 13:54 UTC, AnastasiaKozhemyachko commented on src/components/HeaderUser/HeaderUser.tsx
> +              console.log(userData.profileObj);
console.log

2021-07-09 13:54 UTC, AnastasiaKozhemyachko commented on src/components/HeaderUser/HeaderUser.tsx
> +          if (userData)
Don't use too much nesting and make a separate function better

2021-07-12 07:58 UTC, AnastasiaKozhemyachko requested changes

2021-07-12 07:58 UTC, AnastasiaKozhemyachko commented on src/pages/HomePage/HomePage.tsx
> +          <SubmenuItem name={'Item 1'}>
why such a name('Item 1')?

2021-07-12 09:36 UTC, ZZH0C commented on src/pages/HomePage/HomePage.tsx
> +          <SubmenuItem name={'Item 1'}>
changed to mock props value

2021-07-12 10:36 UTC, bondarchukse commented on src/components/HeaderLogo/HeaderLogo.stories.tsx
> +import { HeaderLogo } from './HeaderLogo';import { ComponentMeta, ComponentStory } from '@storybook/react';import React from 'react';export default {  title: 'UI/HeaderLogo',  component: Header
something went wrong with your stories, please fix it!

2021-07-12 10:36 UTC, bondarchukse commented on src/components/HeaderUser/HeaderUser.tsx
> +  const emptyProfilePictureSrc =
you should not store any hardcode information at the component level. User separated custom hook to provide config information!

2021-07-12 10:36 UTC, bondarchukse commented on src/components/HeaderUser/HeaderUser.tsx
> +  const [profileData, setProfileSrc] = useState({
this hook is useless! It may be a potential confusing and bug reason. Do not duplicate data in different state levels! you can use simple `if` statement instead (probably useMemo to avoid additional renders)

2021-07-12 10:36 UTC, bondarchukse commented on src/components/HeaderUser/HeaderUser.tsx
> +export const HeaderUser: React.FC<HeaderUserProps> = ({ children }) => {
try to pass user data as a prop from the top level! your UI components should be a foolish!

2021-07-12 10:36 UTC, bondarchukse commented on src/hooks/useUserData.tsx
> +      return {
use `...state ` spread for the new object creation. (you can forget about this when add new property to the state later!)

2021-07-12 10:36 UTC, bondarchukse commented on src/hooks/useUserData.tsx
> +        userData: action.user as UserState | null,
action payload is excess for the logout action.
````
{
  userData: null,
  isLogged: false
}
````
will do the same without additional code and action payload

2021-07-12 10:36 UTC, bondarchukse commented on src/pages/HomePage/HomePage.tsx
> +  const responseGoogle = (
need to handle login errors. Try to close google auth window on login to test it

2021-07-12 10:36 UTC, bondarchukse commented on src/pages/HomePage/HomePage.tsx
> +export const UserContext = React.createContext<UserState>(
to move context and all context staff to the separated hook file

2021-07-13 07:55 UTC, AnastasiaKozhemyachko requested changes

2021-07-13 07:55 UTC, AnastasiaKozhemyachko commented on src/pages/HomePage/HomePage.tsx
> +          clientId="386327906890-ce0q1vn2cja1ellekvjj6hmqah4g901c.apps.googleusercontent.com"
if it's the same, create a constant for it

2021-07-13 07:55 UTC, AnastasiaKozhemyachko commented on src/pages/HomePage/HomePage.tsx
> +          <NavbarItem isActive={testPropsNavBarOff.isActive}>
why do you use a lot of repetitive code?

2021-07-13 07:55 UTC, AnastasiaKozhemyachko commented on src/pages/HomePage/HomePage.tsx
> +  const responseFailure = (resp: any) => {
don't use any

2021-07-13 08:28 UTC, AnastasiaKozhemyachko requested changes

2021-07-13 08:28 UTC, AnastasiaKozhemyachko commented on src/components/HeaderUser/HeaderUser.tsx
> +  if (userData) {
don't use too much nesting
you can do this:
```
if (!userData) { return; }
if ('profileObj' in userData) {.....
```

2021-07-14 09:27 UTC, merged