Feature/UI components messages
ZZH0C/react-seed pull request #3
Opened 2021-07-14 10:02 UTC by ZZH0C

2021-07-14 15:44 UTC, AnastasiaKozhemyachko requested changes

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useCreateMessagesUi.tsx
> +    if (e.name === 'From') result.from = e.value;
use switch

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useCreateMessagesUi.tsx
> +      result.date = `${messageDate.getDate()}-${messageDate.getMonth()}-${messageDate.getFullYear()}`;
use a separate function returning format data

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +      loadOneMessage(messageId, userData.accessToken).then((r: any) =>
what is r?

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +      loadOneMessage(messageId, userData.accessToken).then((r: any) =>
don't use any

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +    snippet: any;
don't use any

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +    date: string;
use interface

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +  if (text.text === '') {
you can write if (!text.text) {

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/pages/MessagePage/MessagePage.tsx
> +    <>
where is the tag?

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useCreateMessagesUi.tsx
> +    if (e.name === 'Subject') result.title = e.value;
what is e?

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/hooks/useCreateMessagesUi.tsx
> +  snippet: any;
don't use any

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/global.scss
> +  padding: 1em;
why are you using em instead of rem?

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/global.scss
> +  padding-top: 20px;
use rem

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/global.scss
> +    margin: 0.5em 0;
It is better not to use specific tags but to target the class(add a class to the spans you span)

2021-07-14 15:44 UTC, AnastasiaKozhemyachko commented on src/api/userMessages/userMessages.tsx
> +  return await message;
why are you using 2 await?

2021-07-15 07:58 UTC, bondarchukse commented on src/App.tsx
> +const clientId =
please, put all constants to the separated file `config.js` for example.

2021-07-15 07:58 UTC, bondarchukse commented on src/App.tsx
> +      dispatch({ type: 'logIn', user: response, isLogged: true });
1. `isLogged` action field is excess. You can determinate it inside reducer basing on `user` property. 
2. actions have sigtature `{ type: string, payload: any }` usually. This is not a strict rule, but it makes action processing more easy and more clear

2021-07-15 07:58 UTC, bondarchukse commented on src/App.tsx
> +    dispatch({ type: 'logOut', user: null, isLogged: false });
you don't need send any data for that action!

2021-07-15 07:58 UTC, bondarchukse commented on src/App.tsx
> +    <>
Needs to think about how to split login and router functionality. You are risking to have a frankenstein here))

2021-07-15 07:58 UTC, bondarchukse commented on src/api/userMessages/userMessages.tsx
> +const getMessage = async (id: string | unknown, token: string | null) => {
why id is unknown?

2021-07-15 07:58 UTC, bondarchukse commented on src/components/ButtonLink/ButtonLink.tsx
> +    <Link to={href}>
this is a mistake from semantic point of view. This code will produce
````
<a href="...">
  <button>Text</button>
</a>
````

2021-07-15 07:58 UTC, bondarchukse commented on src/components/MessageFull/MessageFull.tsx
> +export const MessageFull: React.FC<MessageFullProps> = ({
`MessageFull` component name should says about component logic. This is minor thing, but try to figure out better names in future

2021-07-15 07:58 UTC, bondarchukse commented on src/components/MessageFull/MessageFull.tsx
> +  text?: string;
`text`? why not children?

2021-07-15 07:58 UTC, bondarchukse commented on src/hooks/useCreateMessagesUi.tsx
> +export const sortMessageData = (messageData: GoogleMessage) => {
try to refactor this part of the code with lodash functions.

it would be 
```
import { filter, map, fromPairs } from 'lodash';

interface MailHeaders {
  From?: string;
  Subject?: string;
  Date?: string;
}

// pick up needed headers from message
const headersList = ['From', 'Subject', 'Date'];
const filteredHeaders = filter(messageData.payload.headers, ({ name }) => headersList.includes(name));

// map headers asn key-value pair -> [['From', 'from value'], ... ]
const pairs = map(filteredHeaders, ({ name, value }) => [name, value]);

// create object
const headers: MailHeaders = fromPairs(pairs);

// You are able to pick up data as object properties
// <div>headers?.From</div>

2021-07-15 07:58 UTC, bondarchukse commented on src/hooks/useCreateMessagesUi.tsx
> +    text: messageData.payload.parts[0].body.data,
`parts[0]`  this is a bad approach. You should not access to the array elements by index.

2021-07-15 07:58 UTC, bondarchukse commented on src/hooks/useCreateMessagesUi.tsx
> +          const messageDate = new Date(element.value);
you will have current date for empty string
you may have invalid date object here

2021-07-15 07:58 UTC, bondarchukse commented on src/hooks/useGetMessages.tsx
>    const [state, setState] = useState<any>([]);
`state, setState` are bad names!!!! `messages, setMessages` would be better

2021-07-15 07:58 UTC, bondarchukse commented on src/pages/MessagePage/MessagePage.tsx
> +    <>
it's ok. this is shortend for <React.Fragment>

2021-07-15 11:36 UTC, ZZH0C commented on src/components/ButtonLink/ButtonLink.tsx
> +    <Link to={href}>
Why this is a mistake?

2021-07-15 11:49 UTC, bondarchukse commented on src/components/ButtonLink/ButtonLink.tsx
> +    <Link to={href}>
https://overcoder.net/q/9449/%D0%BC%D0%BE%D0%B3%D1%83-%D0%BB%D0%B8-%D1%8F-%D0%B2%D0%BB%D0%BE%D0%B6%D0%B8%D1%82%D1%8C-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82-ltbuttongt-%D0%B2-ltagt-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D1%8F-html5

2021-07-19 08:34 UTC, merged